### ISSUE TITLE
Unit names don't align with units

### ISSUE THREAD

**Issue by StephenJRead** [CompCogNeuro/sims#1]
This may not have been implemented yet, but I notice that the unit names on the network do not align with the units.
Also, I don't see where the names for the units are defined anywhere, so I was curious how that was done.

**Comment by rcoreilly** [comment]
It is done by adding labels separately -- see ConfigNetView method.  unit names are not included in the core api to keep things simpler, and labels are much more flexible.  but as you note, the alignment is only approximate.  on my system it is still aligned closely enough that it is usable -- please post screenshot if otherwise on yours.

**Comment by StephenJRead** [comment]
<img width="1872" alt="Screen Shot 2019-08-31 at 7 37 56 PM" src="https://user-images.githubusercontent.com/21046859/64071101-10410c00-cc27-11e9-98df-75fbae7794c0.png">

**Comment by rcoreilly** [comment]
Looks like a mac -- retina display?  It turns out that when I run on my mac laptop's native display (instead of external monitor I usually use) I replicate this bug, although it is slightly different.  Thanks for the report.

**Comment by StephenJRead** [comment]
I have a Mac 13 inch 2018 MacBook Pro.  But I’m pretty sure the screenshot is on my LG external monitor.  I tried changing the resolutions around, and it actually does change how well they line up, but I can’t find a resolution where they line up sufficiently well.

On Aug 31, 2019, at 9:10 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like a mac -- retina display? It turns out that when I run on my mac laptop's native display (instead of external monitor I usually use) I replicate this bug, although it is slightly different. Thanks for the report.

**Comment by rcoreilly** [comment]
fixed -- was doing word wrapping -- set style to stick to label format
