### ISSUE TITLE
a_not_b sim crashes if you hit TrnTrlTable as instructed in ReadMe

### ISSUE THREAD

**Issue by StephenJRead** [CompCogNeuro/sims#10]
If you follow the instructions in the ReadMe for the a_not_b sim, it tells you to click the TrnTrlTable tab and then click Init, Train.  If you do that the program exits.  However, if you **first** click Init and then click the TrnTrlTable tab, everything works properly and the program does not crash.

**Comment by rcoreilly** [comment]
I'm not able to replicate -- which OS?

**Comment by StephenJRead** [comment]
Mac Mojave’s

Sent from my iPhone

On Apr 17, 2020, at 2:08 AM, rcoreilly <notifications@github.com> wrote:

﻿

I'm not able to replicate -- which OS?

**Comment by StephenJRead** [comment]
This only happens if you do this before you hit Init.  Once you hit Init, there is no problem.

Stephen J. Read, Mendel B. Silberberg Professor of Social Psychology
3620 McClintock Ave, 501 SGM
University of Southern California
Los Angeles, CA 90089-1061
read@usc.edu<mailto:read@usc.edu>

On Apr 17, 2020, at 2:08 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm not able to replicate -- which OS?

**Comment by rcoreilly** [comment]
Yeah I did it multiple times *without* hitting Init first.  can you post the stack trace from the crash?  run it from the terminal if you don't see the stack trace.

**Comment by StephenJRead** [comment]
This is what shows up in the terminal window.

Last login: Fri Apr 17 12:51:52 on ttys000
/Applications/Emergent\ Go\ ver\ 1.01/mac\ binaries/ch10/a_not_b ; exit;
(base) StephenReadsMBP:~ read$ /Applications/Emergent\ Go\ ver\ 1.01/mac\ binaries/ch10/a_not_b ; exit;
OpenGL version 4.1 INTEL-12.10.17
panic: runtime error: makeslice: len out of range

goroutine 37 [running]:
github.com/emer/etable/etview<http://github.com/emer/etable/etview>.(*TableView).LayoutSliceGrid(0xc0001d0800, 0x53c7200)
/Users/oreilly/go/src/github.com/emer/etable/etview/tableview.go:411<http://github.com/emer/etable/etview/tableview.go:411> +0x276
github.com/goki/gi/giv<http://github.com/goki/gi/giv>.(*SliceViewBase).Render2D(0xc0001d0800)
/Users/oreilly/go/src/github.com/goki/gi/giv/sliceviewbase.go:848<http://github.com/goki/gi/giv/sliceviewbase.go:848> +0x1ba
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Node2DBase).Render2DTree(0xc0001d0800)
/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:712<http://github.com/goki/gi/gi/node2d.go:712> +0x78
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*WidgetBase).ReRender2DTree(0xc0001d0800)
/Users/oreilly/go/src/github.com/goki/gi/gi/widget.go:425<http://github.com/goki/gi/gi/widget.go:425> +0x23d
github.com/goki/gi/giv<http://github.com/goki/gi/giv>.(*SliceViewBase).Render2D(0xc0001d0800)
/Users/oreilly/go/src/github.com/goki/gi/giv/sliceviewbase.go:850<http://github.com/goki/gi/giv/sliceviewbase.go:850> +0x1c8
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Layout).Render2DChildren(0xc000315b80)
/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:1142<http://github.com/goki/gi/gi/layout.go:1142> +0xb9
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Frame).Render2D(0xc000315b80)
/Users/oreilly/go/src/github.com/goki/gi/gi/frame.go:170<http://github.com/goki/gi/gi/frame.go:170> +0xc4
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Node2DBase).Render2DTree(0xc000315b80)
/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:712<http://github.com/goki/gi/gi/node2d.go:712> +0x78
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*WidgetBase).ReRender2DTree(0xc000315b80)
/Users/oreilly/go/src/github.com/goki/gi/gi/widget.go:425<http://github.com/goki/gi/gi/widget.go:425> +0x23d
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*WidgetBase).FullReRenderIfNeeded(0xc000315b80, 0xc000315b80)
/Users/oreilly/go/src/github.com/goki/gi/gi/widget.go:351<http://github.com/goki/gi/gi/widget.go:351> +0x114
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Frame).Render2D(0xc000315b80)
/Users/oreilly/go/src/github.com/goki/gi/gi/frame.go:163<http://github.com/goki/gi/gi/frame.go:163> +0x31
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Layout).Render2DChildren(0xc00019b080)
/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:1142<http://github.com/goki/gi/gi/layout.go:1142> +0xb9
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*TabView).Render2D(0xc00019b080)
/Users/oreilly/go/src/github.com/goki/gi/gi/tabview.go:489<http://github.com/goki/gi/gi/tabview.go:489> +0xb6
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Node2DBase).Render2DTree(0xc00019b080)
/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:712<http://github.com/goki/gi/gi/node2d.go:712> +0x78
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Viewport2D).ReRender2DNode(0xc0005bca80, 0x7722408, 0xc00019b080)
/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:258<http://github.com/goki/gi/gi/viewport.go:258> +0xdf
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Viewport2D).UpdateNode(0xc0005bca80, 0x7722408, 0xc00019b080)
/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:701<http://github.com/goki/gi/gi/viewport.go:701> +0x1cf
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Viewport2D).UpdateNodes(0xc0005bca80)
/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:682<http://github.com/goki/gi/gi/viewport.go:682> +0x1a4
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Viewport2D).NodeUpdated(0xc0005bca80, 0x7722408, 0xc00019b080, 0x1, 0x4e79e20, 0xc00d48cc18)
/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:581<http://github.com/goki/gi/gi/viewport.go:581> +0x166
github.com/goki/gi/gi.SignalViewport2D<http://github.com/goki/gi/gi.SignalViewport2D>(0x53d0300, 0xc0005bca80, 0x53cf640, 0xc00019b080, 0x1, 0x4e79e20, 0xc00d48cc18)
/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:535<http://github.com/goki/gi/gi/viewport.go:535> +0x134
github.com/goki/ki/ki<http://github.com/goki/ki/ki>.(*Signal).Emit(0xc00019b0d8, 0x53cf640, 0xc00019b080, 0x1, 0x4e79e20, 0xc00d48cc18)
/Users/oreilly/go/src/github.com/goki/ki/ki/signal.go:162<http://github.com/goki/ki/ki/signal.go:162> +0x1a5
github.com/goki/ki/ki<http://github.com/goki/ki/ki>.(*Node).UpdateEnd(0xc00019b080, 0xc000675901)
/Users/oreilly/go/src/github.com/goki/ki/ki/node.go:1912<http://github.com/goki/ki/ki/node.go:1912> +0x20a
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*TabView).SelectTabIndex(0xc00019b080, 0x1, 0xc00089ec80, 0x53cf200, 0xc00089ec80)
/Users/oreilly/go/src/github.com/goki/gi/gi/tabview.go:205<http://github.com/goki/gi/gi/tabview.go:205> +0x1ce
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*TabView).SelectTabIndexAction(0xc00019b080, 0x1)
/Users/oreilly/go/src/github.com/goki/gi/gi/tabview.go:213<http://github.com/goki/gi/gi/tabview.go:213> +0x39
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*TabView).InsertTabOnlyAt.func1(0x53cf640, 0xc00019b080, 0x53cf200, 0xc00089ec80, 0x0, 0x4e79d60, 0xc000a04770)
/Users/oreilly/go/src/github.com/goki/gi/gi/tabview.go:112<http://github.com/goki/gi/gi/tabview.go:112> +0xe6
github.com/goki/ki/ki<http://github.com/goki/ki/ki>.(*Signal).Emit(0xc0008a04f0, 0x53cf200, 0xc00089ec80, 0x0, 0x4e79d60, 0xc000a04770)
/Users/oreilly/go/src/github.com/goki/ki/ki/signal.go:162<http://github.com/goki/ki/ki/signal.go:162> +0x1a5
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Action).ButtonRelease(0xc00089ec80)
/Users/oreilly/go/src/github.com/goki/gi/gi/action.go:222<http://github.com/goki/gi/gi/action.go:222> +0x113
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*ButtonBase).MouseEvent.func1(0x53cf200, 0xc00089ec80, 0x53d0b80, 0xc0005db000, 0x0, 0x4fd9540, 0xc00d3155c0)
/Users/oreilly/go/src/github.com/goki/gi/gi/buttons.go:446<http://github.com/goki/gi/gi/buttons.go:446> +0xcd
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*WinEventRecv).Call(...)
/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:2079<http://github.com/goki/gi/gi/window.go:2079>
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Window).SendEventSignal(0xc0005db000, 0x5363280, 0xc00d3155c0, 0x1)
/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:2225<http://github.com/goki/gi/gi/window.go:2225> +0x569
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Window).ProcessEvent(0xc0005db000, 0x5363280, 0xc00d3155c0)
/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1592<http://github.com/goki/gi/gi/window.go:1592> +0x9cf
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Window).EventLoop(0xc0005db000)
/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1519<http://github.com/goki/gi/gi/window.go:1519> +0x36
github.com/goki/gi/gi<http://github.com/goki/gi/gi>.(*Window).StartEventLoop(0xc0005db000)
/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:879<http://github.com/goki/gi/gi/window.go:879> +0x6d
main.mainrun()
/Users/oreilly/go/src/github.com/CompCogNeuro/sims/ch10/a_not_b/a_not_b.go:945<http://github.com/CompCogNeuro/sims/ch10/a_not_b/a_not_b.go:945> +0x1fa
main.main.func1()
/Users/oreilly/go/src/github.com/CompCogNeuro/sims/ch10/a_not_b/a_not_b.go:48<http://github.com/CompCogNeuro/sims/ch10/a_not_b/a_not_b.go:48> +0x20
github.com/goki/gi/gimain.Main.func1<http://github.com/goki/gi/gimain.Main.func1>(0x5391720, 0x64dd9a0)
/Users/oreilly/go/src/github.com/goki/gi/gimain/gimain.go:30<http://github.com/goki/gi/gimain/gimain.go:30> +0x24
github.com/goki/gi/oswin/driver/glos.Main.func1<http://github.com/goki/gi/oswin/driver/glos.Main.func1>()
/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/glos/app.go:87<http://github.com/goki/gi/oswin/driver/glos/app.go:87> +0x40
created by github.com/goki/gi/oswin/driver/glos.Main<http://github.com/goki/gi/oswin/driver/glos.Main>
/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/glos/app.go:86<http://github.com/goki/gi/oswin/driver/glos/app.go:86> +0x87
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...5 completed.

[Process completed]

Stephen J. Read, Mendel B. Silberberg Professor of Social Psychology
3620 McClintock Ave, 501 SGM
University of Southern California
Los Angeles, CA 90089-1061
read@usc.edu<mailto:read@usc.edu>

On Apr 17, 2020, at 12:38 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:



Yeah I did it multiple times without hitting Init first. can you post the stack trace from the crash? run it from the terminal if you don't see the stack trace.

**Comment by rcoreilly** [comment]
I think you have an old version of the sims -- that trace doesn't line up with the current code -- can you try downloading current release and see what happens?  there were specific fixes for that issue.

**Comment by StephenJRead** [comment]
Okay, will do. I think I have 1.01

Stephen J. Read, Mendel B. Silberberg Professor of Social Psychology
3620 McClintock Ave, 501 SGM
University of Southern California
Los Angeles, CA 90089-1061
read@usc.edu<mailto:read@usc.edu>

On Apr 17, 2020, at 1:17 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:



I think you have an old version of the sims -- that trace doesn't line up with the current code -- can you try downloading current release and see what happens? there were specific fixes for that issue.

**Comment by StephenJRead** [comment]
Just tried the 1.03 version and no problem.  Thanks.

Stephen J. Read, Mendel B. Silberberg Professor of Social Psychology
3620 McClintock Ave, 501 SGM
University of Southern California
Los Angeles, CA 90089-1061
read@usc.edu<mailto:read@usc.edu>

On Apr 17, 2020, at 1:17 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:



I think you have an old version of the sims -- that trace doesn't line up with the current code -- can you try downloading current release and see what happens? there were specific fixes for that issue.
