### ISSUE TITLE
On Mac executables can be started by double clicking

### ISSUE THREAD

**Issue by StephenJRead** [CompCogNeuro/sims#11]
Contrary to the instructions on the Read Me, Mac executables can be started by double clicking, they do not require a control click.  Double-clicking on the executable opens a Mac Terminal window and the program starts.

**Comment by rcoreilly** [comment]
I think this might vary depending on os settings or something else -- maybe the SDK target when building or something -- anyway, l will update the note to a "if it doesn't work to double click.." kind of thing.
