### ISSUE TITLE
dyslex crashed

### ISSUE THREAD

**Issue by MaryZolfaghar** [CompCogNeuro/sims#17]
- Open Trained Wts
- Train
- TrnEpcPlot
- Stop
- Init <- crashed

oshadow:ch9 Maryam$ ./dyslex 
2020/06/03 12:01:33 No data points
2020/06/03 12:01:33 No data points
2020/06/03 12:01:33 No data points
2020/06/03 12:01:33 No data points
2020/06/03 12:01:33 No data points
2020/06/03 12:01:33 No data points
2020/06/03 12:01:33 No data points
2020/06/03 12:01:33 No data points
2020/06/03 12:01:33 No data points
2020/06/03 12:01:33 No data points
panic: runtime error: index out of range [1] with length 1

goroutine 7 [running]:
github.com/emer/etable/eplot.(*Plot2D).GenPlotBar(0xc0004d1100)
	/Users/oreilly/go/pkg/mod/github.com/emer/etable@v1.0.2/eplot/barplot.go:129 +0x10e9
github.com/emer/etable/eplot.(*Plot2D).GenPlot(0xc0004d1100)
	/Users/oreilly/go/pkg/mod/github.com/emer/etable@v1.0.2/eplot/eplot2d.go:274 +0xe0
github.com/emer/etable/eplot.(*Plot2D).Style2D(0xc0004d1100)
	/Users/oreilly/go/pkg/mod/github.com/emer/etable@v1.0.2/eplot/eplot2d.go:595 +0x84
github.com/goki/gi/gi.(*Node2DBase).Style2DTree.func1(0x54b9860, 0xc0004d1100, 0x6, 0x517aaa0, 0xc000818000, 0x1)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/node2d.go:756 +0x51
github.com/goki/ki/ki.(*Node).FuncDownMeFirst(0xc000818000, 0x6, 0x517aaa0, 0xc000818000, 0x528cbe8)
	/Users/oreilly/go/pkg/mod/github.com/goki/ki@v1.0.0/ki/node.go:1650 +0x778
github.com/goki/gi/gi.(*Node2DBase).Style2DTree(0xc000818000)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/node2d.go:750 +0x109
github.com/goki/gi/gi.(*Node2DBase).FullRender2DTree(0xc000818000)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/node2d.go:691 +0x56
github.com/goki/gi/gi.(*Viewport2D).FullRender2DTree(0xc000818000)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/viewport.go:548 +0x91
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes(0xc000818000)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/viewport.go:813 +0x4d5
github.com/goki/gi/gi.(*Viewport2D).SetNeedsFullRender(0xc000818000)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/viewport.go:773 +0x51
main.(*Sim).ConfigGui.func2(0x54c4ae0, 0xc000803000, 0x54bc2e0, 0xc0011ec600, 0x0, 0x0, 0x0)
	/Users/oreilly/go/src/github.com/CompCogNeuro/sims/ch9/dyslex/dyslex.go:1398 +0x41
github.com/goki/ki/ki.(*Signal).Emit(0xc0011edea8, 0x54bc2e0, 0xc0011ec600, 0x0, 0x0, 0x0)
	/Users/oreilly/go/pkg/mod/github.com/goki/ki@v1.0.0/ki/signal.go:162 +0x1a5
github.com/goki/gi/gi.(*Action).ButtonRelease(0xc0011ec600)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/action.go:222 +0x112
github.com/goki/gi/gi.(*ButtonBase).MouseEvent.func1(0x54bc2e0, 0xc0011ec600, 0x54c4ae0, 0xc000803000, 0x0, 0x50b8580, 0xc017ec4f80)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/buttons.go:438 +0xcd
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc01fb4bcf8, 0x54c4ae0, 0xc000803000, 0x0, 0x50b8580, 0xc017ec4f80)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc000803190, 0x5470660, 0xc017ec4f80, 0x1)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/events.go:237 +0x54f
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc000803000, 0x5470660, 0xc017ec4f80)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/window.go:1521 +0x7ac
github.com/goki/gi/gi.(*Window).EventLoop(0xc000803000)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/window.go:1448 +0x36
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc000803000)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gi/window.go:854 +0x6d
main.mainrun()
	/Users/oreilly/go/src/github.com/CompCogNeuro/sims/ch9/dyslex/dyslex.go:1641 +0x6b
main.main.func1()
	/Users/oreilly/go/src/github.com/CompCogNeuro/sims/ch9/dyslex/dyslex.go:47 +0x20
github.com/goki/gi/gimain.Main.func1(0x5484560, 0x68dc280)
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/gimain/gimain.go:31 +0x24
github.com/goki/gi/oswin/driver/glos.Main.func1()
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/oswin/driver/glos/app.go:87 +0x40
created by github.com/goki/gi/oswin/driver/glos.Main
	/Users/oreilly/go/pkg/mod/github.com/goki/gi@v1.0.1/oswin/driver/glos/app.go:86 +0x87

**Comment by rcoreilly** [comment]
this has already been fixed in latest code with various rewrites of plot code.
