### ISSUE TITLE
Act_M doesn't display until many cycles after Act displays

### ISSUE THREAD

**Issue by StephenJRead** [CompCogNeuro/sims#2]
Maybe I'm misunderstanding something fundamental, but when I display the Act variable on the network, and run the cats and dogs, the Act variable starts to increase before cycle 20 or so, but the ActM variable does not start to display until almost cycle 70.

**Comment by rcoreilly** [comment]
ActM reflects activity at *end* of minus phase, which occurs at cycle 75.  until that point it reflects the previous minus phase or 0 if initialized.
