### ISSUE TITLE
r.Wt does not show weights

### ISSUE THREAD

**Issue by Zy-Zhenyu-Zhu** [CompCogNeuro/sims#29]
Some students in the class can not see the colored blocks for r.Wt - they only got faint greens for the unit they clicked on but no other unit lit up. This has appeared in some simulations in both chapter 3 and 4. Just posting this issue to flag the situation. Will investigate if there is any commonality among the systems those students use

**Comment by rcoreilly** [comment]
You now have to hit the `Init` button before the weights will show up.  If they still don't show up, let me know -- there is another case where there is a bug with this that I'm investigating.

**Comment by rcoreilly** [comment]
I'm assuming this is fixed with the Init button?  reopen if not.
