### ISSUE TITLE
Broken link for ccn_sims_v1.3.3_mac-intel.zip 

### ISSUE THREAD

**Issue by krishnbera** [CompCogNeuro/sims#33]
The link on the repo page seems broken, it says "Not Found". 
I was wondering if there is a way to fix this since a couple of students are still on Intel Macs. 
While I currently advise students to download the previous version v1.3.2 (and it seems to work ok), I was not sure if there were major bug fixes or breaking changes introduced after the previous version.

**Comment by rcoreilly** [comment]
sorry for the delay -- just uploaded a 1.3.3. version for mac-intel.
