### ISSUE TITLE
Neuron: Readme

### ISSUE THREAD

**Issue by StephenJRead** [CompCogNeuro/sims#42]
Under the Leak section it says:
Press the Defaults button on the control panel.  

I believe this is incorrect. I think it should refer to Defaults in the Toolbar, which the second reference to Defaults says.

**Comment by rcoreilly** [comment]
fixed now -- also you can directly edit these .md files on github to make these fixes :)

**Comment by StephenJRead** [comment]
Okay, will do so in the future. I don’t think I had edit privileges on these pages before.
Thanks for fixing it.


Stephen J. Read
Mendel B. Silberberg Professor of Social Psychology
Department of Psychology
University of Southern California
Los Angeles, CA 90089-1061
Website: www.stephenjread.com<http://www.stephenjread.com>




From: rcoreilly ***@***.***>
Date: Sunday, September 1, 2024 at 1:06 PM
To: CompCogNeuro/sims ***@***.***>
Cc: Stephen Read ***@***.***>, Author ***@***.***>
Subject: Re: [CompCogNeuro/sims] Neuron: Readme (Issue #42)

fixed now -- also you can directly edit these .md files on github to make these fixes :)
