### ISSUE TITLE
Settings menu no longer visible

### ISSUE THREAD

**Issue by StephenJRead** [CompCogNeuro/sims#43]
the setting menu for setting things like Light/Dark mode is no longer visible. Should modify instructions to indicate that one can open a contextual menu, by doing a two finger click or a control click on the sim (for the Mac, not sure about Windows).

**Comment by kkoreilly** [comment]
Yes, that was an intentional change, and the right click / two finger click works on all platforms. I will update the documentation to clarify that.

**Comment by StephenJRead** [comment]
I remember Randy saying he was playing with the toolbar to make it take up less room, so I knew that part was planned.
Thanks for doing this.


Stephen J. Read
Mendel B. Silberberg Professor of Social Psychology
Department of Psychology
University of Southern California
Los Angeles, CA 90089-1061
Website: www.stephenjread.com<http://www.stephenjread.com>




From: kkoreilly ***@***.***>
Date: Thursday, September 5, 2024 at 9:57 PM
To: CompCogNeuro/sims ***@***.***>
Cc: Stephen Read ***@***.***>, Author ***@***.***>
Subject: Re: [CompCogNeuro/sims] Settings menu no longer visible (Issue #43)

Yes, that was an intentional change, and the right click / two finger click works on all platforms. I will update the documentation to clarify that.

**Comment by kkoreilly** [comment]
I updated the simulations website page to correctly describe how to access the settings. (Also, I was the one who redesigned the toolbar to be more space-efficient in https://github.com/cogentcore/core/pull/1197).

**Comment by StephenJRead** [comment]
Ah, sorry for misattributing.  The CogentCore gui is a nice piece of work. Better looking and far more stable.  And I like the fact that people can simply play with simulations in a web browser.
Best, Steve


Stephen J. Read
Mendel B. Silberberg Professor of Social Psychology
Department of Psychology
University of Southern California
Los Angeles, CA 90089-1061
Website: www.stephenjread.com<http://www.stephenjread.com>




From: kkoreilly ***@***.***>
Date: Friday, September 6, 2024 at 12:28 PM
To: CompCogNeuro/sims ***@***.***>
Cc: Stephen Read ***@***.***>, Author ***@***.***>
Subject: Re: [CompCogNeuro/sims] Settings menu no longer visible (Issue #43)

I updated the simulations website page to correctly describe how to access the settings. (Also, I was the one who redesigned the toolbar to be more space-efficient in cogentcore/core#1197<https://urldefense.com/v3/__https:/github.com/cogentcore/core/pull/1197__;!!LIr3w8kk_Xxm!vMn_B_ZS_nD2tKd98ntHppdDXXVn6nwdG_3VElDE3sz9VwOnq6FBIXSHHtOl0rGoVWHhn-h82I-d786spDXv$>).
