### ISSUE TITLE
Ch9 Test Trial button is missing

### ISSUE THREAD

**Issue by BB2500** [CompCogNeuro/sims#46]
Right before question 9.2 it is requested that we press the "Test Trial" button ("First, click back to viewing the Network, and click on Act to view activations. Then, do Test Init and then Step Trial. Review the activation settling using the Time VCR buttons on the lower right of the Network. Click Test Trial to go through each type of trial in the Test patterns, and review activation settling for each trial."). However, this button is missing from this task (but not from others). 
![image](https://github.com/user-attachments/assets/1bde0bc4-fd80-480e-9e5b-3389b0e19a95)
How can this be fixed?

**Comment by rcoreilly** [comment]
sorry this is meant to be `Step Trial` again, under the Test section. we will improve this whole stepping GUI soon too.

**Comment by BB2500** [comment]
Thank you very much!
