### ISSUE TITLE
On Windows windows don't open

### ISSUE THREAD

**Issue by StephenJRead** [CompCogNeuro/sims#7]
This is related to an issue that I reported earlier, but I can't find where I posted it before. Anyway, I reported earlier that when opening some of the projects from Chapter 2, either detector or neuron that on Windows 10 the main project window didn't open, but that with some playing around with Windows split screen function they were able to get it to open.  Randy asked people to look at the screen info in GoGi preferences.  However, one of my students says that while she can get the project window to open properly, when she tries to open either the TestCycLog for the neuron project that the window does not show up and she also cannot get the GoGi preferences window to show up.

**Comment by rcoreilly** [comment]
I got this report from a student:

> Hover your cursor over the detector.exe icon in the taskbar and when the preview of the application pops up, either double click or right click the preview and press maximize.

it seems like it is opening the windows in a minimized state -- need to try on windows myself at some point to debug.  maybe closing a sim with the window minimized causes this problem?  it does try to remember the size so that might be it?

**Comment by StephenJRead** [comment]
This sounds similar to something one of my students found.  Although it does happen when the project is opened the first time, I believe.

Stephen J. Read, Mendel B. Silberberg Professor of Social Psychology
3620 McClintock Ave, 501 SGM
University of Southern California
Los Angeles, CA 90089-1061
read@usc.edu<mailto:read@usc.edu>

On Apr 17, 2020, at 2:05 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:



I got this report from a student:

Hover your cursor over the detector.exe icon in the taskbar and when the preview of the application pops up, either double click or right click the preview and press maximize.

it seems like it is opening the windows in a minimized state -- need to try on windows myself at some point to debug. maybe closing a sim with the window minimized causes this problem? it does try to remember the size so that might be it?

**Comment by rcoreilly** [comment]
this is now fixed.  was storing zero sizes.
